spring:
  application:
    name: telegram-bot-demo
  datasource:
    url: jdbc:postgresql://localhost:5438/groupgoalsbot?currentSchema=boot
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: boot

telegram:
  bot:
    token: 7391568163:AAGKixgnapRdXHE4j2K7kQUetEq-BexHuiw
    name: goalbot

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG