spring:
  application:
    name: telegram-bot-demo
  datasource:
    url: jdbc:postgresql://localhost:5438/groupgoalsbot?currentSchema=boot
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: boot
  profiles:
    active: dev